### ISSUE TITLE
Consider adding ssh for git cloning submodules

### ISSUE THREAD

**Issue by muelli** [aergus/dockerfiles#10]
AFAICS git clone does not work for repositories fetched via SSH.
My life would be a tiny bit happier if I could have my CI build a document which is composed of several sub-documents living in git sub-modules.

**Comment by aergus** [comment]
Fair enough; cloning Git repositories via SSH is not uncommon and installing SSH doesn't add much storage overhead, so I've added it in 411e9bf4a58789b755ee188a6069a475bd07b6d9.

The image on Docker Hub has been updated as well.

**Comment by aergus** [comment]
I realized that `ssh` is a metapackage for an SSH client *and* server, so I updated the package list to only install `openssh-client` (cf. f1484eb2e8d6995cafb480f52870c0bb17878e77).
