### ISSUE TITLE
Consider tagging dockerhub builds

### ISSUE THREAD

**Issue by daraul** [aergus/dockerfiles#11]
I use your image to compile my resume and upload it, and as part of best practice I should be using a tag, instead of latest to ensure future builds don't fail. Would you consider tagging your builds so that they can then be used?

**Comment by aergus** [comment]
As this image is supposed to deliver the most recent TeX Live packages in Debian, using older builds is not really an anticipated use case.

However, I understand that some people might want to do that anyway, so from now on I will also create builds tagged with the date of the build. (The [first one](https://hub.docker.com/layers/aergus/latex/2020-04-29/images/sha256-95e977cb74ef166ce428145f5ef54a2baa36472d1d57512f3726d3e8d128a531) was built yesterday.)

**Comment by daraul** [comment]
I understand, and thank you for compromising. I've just been bitten in the butt before for using `latest`. I'll keep an eye out and update periodically, though. Thanks!
